sdfat: use timespec64 for inode timestamps
Inode timestamps are stored in struct timespec64 since the vfs was
converted (5a919fb4461f), but sdfat only switches sdfat_timespec_t and
CURRENT_TIME_SEC to the timespec64 variants when
LINUX_VERSION_CODE >= 4.18. On 4.14 the driver therefore still uses
struct timespec and fails to build:

  fs/sdfat/sdfat.c: error: incompatible types when assigning to type
  'struct timespec64' from type 'struct timespec'

Lower the version check to 4.14 so that sdfat_timespec_t is a struct
timespec64 and CURRENT_TIME_SEC uses timespec64_trunc(), as the exfat
and incfs drivers already do.